"""updating pokemon db

Revision ID: 033233213f39
Revises: d2a7db600bed
Create Date: 2023-11-18 13:48:18.347648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033233213f39'
down_revision = 'd2a7db600bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprite', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ability_description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('ability_description')
        batch_op.drop_column('sprite')

    # ### end Alembic commands ###
