"""removing team

Revision ID: 530a69f6c355
Revises: b85616491872
Create Date: 2023-11-13 18:23:45.884740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '530a69f6c355'
down_revision = 'b85616491872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('team')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', postgresql.BYTEA(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
