"""updating pokemon table

Revision ID: d2a7db600bed
Revises: 1da75d496878
Create Date: 2023-11-17 16:34:33.997509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a7db600bed'
down_revision = '1da75d496878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poke_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ability', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('hp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('defense', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attack', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_xp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('base_xp')
        batch_op.drop_column('attack')
        batch_op.drop_column('defense')
        batch_op.drop_column('hp')
        batch_op.drop_column('ability')
        batch_op.drop_column('poke_type')

    # ### end Alembic commands ###
